defaults:
  - base_mppi

mppi_mode: "halton-spline"  # halton-spline, simple
sampling_method: "halton"   # halton, random
num_samples: 100  
horizon: 100
device: "cpu"
lambda_: 0.05
u_min: [-0.2, -0.2, -0.8]
u_max: [0.6, 0.6, 0.8]
noise_sigma: [[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]]
update_cov: False
rollout_var_discount: 0.95
sample_null_action: False
noise_abs_cost: False
filter_u: False
use_priors: False
