#!/usr/bin/env python3

import hydra
import rospy

from monitor import Viewer


if __name__ == "__main__":
    rospy.init_node('visualisation', anonymous=True)

    rospy.loginfo(f'Creating visualizer for the physical world.')

    run_frequency = rospy.get_param('~run_frequency')
    config = rospy.get_param('~config')
    layout = rospy.get_param('~layout')

    hydra.initialize(config_path="../config", version_base=None)
    hydra_config = hydra.compose(config)

    viewer = Viewer.build(hydra_config, layout)

    rate = rospy.Rate(run_frequency)
    while not rospy.is_shutdown():
        viewer.run()

        rate.sleep()

    viewer.destroy()