range_x: [-6., 6.]
range_y: [-6., 6.]

camera:
    pos: [-6., 0., 5.]
    tar: [0., 0., 0.]

scheduler:
    step: 0.1
    goal: [4.0, 4.0]
    mass_threshold: 10.0 
    path_inflation: 0.5

controller:
    pos_tolerance: 0.1  # meters
    yaw_tolerance: 0.1  # radian
 
objects:
    wall:
        type: "box"
        color: [0.0, 0.2, 0.4]
        collision: False
        fixed: True
    chair:
        type: "box"
        size: [0.500, 0.500, 0.700]
        friction: 0.300
        mass: 8.00
        color: [0.9, 0.2, 0.0]
        noise_sigma_size: [0.005, 0.005, 0.0]
        noise_percentage_friction: 0.3
        noise_percentage_mass: 0.3
        fixed: False
        collision: True
    chaise:
        type: "box"
        size: [0.500, 0.500, 0.700]
        friction: 0.300
        mass: 20.00
        color: [0.6, 0.2, 0.0]
        noise_sigma_size: [0.005, 0.005, 0.0]
        noise_percentage_friction: 0.3
        noise_percentage_mass: 0.3
        fixed: False
        collision: True
    table:
        type: "box"
        size: [0.800, 1.600, 0.600]
        friction: 0.300
        mass: 40.00
        color: [0.2, 0.8, 0.0]
        noise_sigma_size: [0.005, 0.005, 0.0]
        noise_percentage_friction: 0.3
        noise_percentage_mass: 0.3
        fixed: False
        collision: True
    bookcase:
        type: "box"
        size: [0.800, 0.600, 1.800]
        friction: 0.300
        mass: 30.00
        color: [0.2, 0.2, 0.8]
        noise_sigma_size: [0.005, 0.005, 0.0]
        noise_percentage_friction: 0.3
        noise_percentage_mass: 0.3
        fixed: False
        collision: True
