
random: False

stationary_percentage: 0.1
stationary_size_noise: 0.5

adjustable_percentage: 0.1
adjustable_size_noise: 0.5

camera:
    pos: [-0, -6., 5.]
    tar: [0., 0., 0.]

scheduler:
    mass_threshold: 15.
    path_inflation: 0.3

controller:
    max_f_contact: 
    pos_tolerance: 0.3  # meters
    yaw_tolerance: 0.1  # radian
    vel_tolerance: 0.1
 
objects:
    wall:
        type: "box"
        color: [0.0, 0.2, 0.4]
        collision: True
        friction: 1.00
        mass: 1000.00
        fixed: True
    chair:
        type: "box"
        size: [0.500, 0.500, 0.700]
        friction: 0.300
        mass: 5.00
        color: [0.9, 0.2, 0.0]
        noise_sigma_size: [0.005, 0.005, 0.0]
        noise_percentage_friction: 0.3
        noise_percentage_mass: 0.
        fixed: False
        collision: True
    chaise:
        type: "box"
        size: [0.500, 0.500, 0.700]
        friction: 1.500
        mass: 30.00
        color: [0.6, 0.2, 0.0]
        noise_sigma_size: [0.005, 0.005, 0.0]
        noise_percentage_friction: 0.3
        noise_percentage_mass: 0.
        fixed: False
        collision: True
    table:
        type: "box"
        size: [0.800, 1.600, 0.600]
        friction: 0.300
        mass: 40.00
        color: [0.2, 0.8, 0.0]
        noise_sigma_size: [0.005, 0.005, 0.0]
        noise_percentage_friction: 0.3
        noise_percentage_mass: 0.3
        fixed: False
        collision: True
    bookcase:
        type: "box"
        size: [0.800, 0.600, 1.800]
        friction: 0.300
        mass: 30.00
        color: [0.2, 0.2, 0.8]
        noise_sigma_size: [0.005, 0.005, 0.0]
        noise_percentage_friction: 0.3
        noise_percentage_mass: 0.3
        fixed: False
        collision: True

    stationary:
        type: "box"
        size: [0.500, 0.500, 0.700]
        friction: 1.500
        mass: 30.00
        color: [0.2, 0.2, 0.2]
        noise_sigma_size: [0.005, 0.005, 0.0]
        noise_percentage_friction: 0.3
        noise_percentage_mass: 0.1
        fixed: False
        collision: True

    adjustable:
        type: "box"
        size: [0.500, 0.500, 0.700]
        friction: 0.500
        mass: 10.00
        color: [0.9, 0.2, 0.0]
        noise_sigma_size: [0.005, 0.005, 0.0]
        noise_percentage_friction: 0.3
        noise_percentage_mass: 0.9
        fixed: False
        collision: True
