name: "Random"
description: "Navigation Among Movable Obstacles: Simulated Approach"

range_x: [-4.0, 4.0]
range_y: [-4.0, 4.0]

goal: [3.5, 3.05]

random: True

environment:
    robot:
        init_state: [-3, -3, 90.0]
