name: "Random"
description: "Navigation Among Movable Obstacles: Simulated Approach"

range_x: [-4.0, 4.0]
range_y: [-4.0, 4.0]

goal: [3.5, 3.05]

random: True

stationary_percentage: 0.01
stationary_size_noise: 0.10

adjustable_percentage: 0.10
adjustable_size_noise: 0.10

environment:
    robot:
        init_state: [-3, -3, 90.0]
