name: "Sandbox"
description: "Navigation Among Movable Obstacles: Simulated Approach"

camera:
    pos: [-6, -6, 5]
    tar: [0, 0, 0]

scheduler:
    step: 0.2
    goal: [4.5, 4.5]

objects:
    wall:
        type: "box"
        color: [0.0, 0.2, 0.4]
        collision: False
        fixed: True
    chair:
        type: "box"
        size: [0.500, 0.500, 0.700]
        friction: 0.300
        mass: 8.00
        color: [0.9, 0.2, 0.0]
        noise_sigma_size: [0.005, 0.005, 0.0]
        noise_percentage_friction: 0.3
        noise_percentage_mass: 0.3
        fixed: False
        collision: True
    chaise:
        type: "box"
        size: [0.500, 0.500, 0.700]
        friction: 0.300
        mass: 20.00
        color: [0.6, 0.2, 0.0]
        noise_sigma_size: [0.005, 0.005, 0.0]
        noise_percentage_friction: 0.3
        noise_percentage_mass: 0.3
        fixed: False
        collision: True
    table:
        type: "box"
        size: [0.800, 1.600, 0.600]
        friction: 0.300
        mass: 40.00
        color: [0.2, 0.8, 0.0]
        noise_sigma_size: [0.005, 0.005, 0.0]
        noise_percentage_friction: 0.3
        noise_percentage_mass: 0.3
        fixed: False
        collision: True
    bookcase:
        type: "box"
        size: [0.800, 0.600, 1.800]
        friction: 0.300
        mass: 30.00
        color: [0.2, 0.2, 0.8]
        noise_sigma_size: [0.005, 0.005, 0.0]
        noise_percentage_friction: 0.3
        noise_percentage_mass: 0.3
        fixed: False
        collision: True

environment:
    size: [10, 10]

    demarcation:
        - wall:
            name: "f-demarcation-wall"
            size: [10.0, 0.2, 0.5]
            init_pos: [0.0, 5.2, 0.0]
            init_ori: [0.0, 0.0, 0.0]
        - wall:
            name: "b-demarcation-wall"
            size: [10.0, 0.2, 0.5]
            init_pos: [0.0, -5.2, 0.0]
            init_ori: [0.0, 0.0, 0.0]
        - wall:
            name: "l-demarcation-wall"
            size: [10.0, 0.2, 0.5]
            init_pos: [-5.2, 0.0, 0.0]
            init_ori: [0.0, 0.0, 90.0]
        - wall:
            name: "r-demarcation-wall"
            size: [10.0, 0.2, 0.5]
            init_pos: [5.2, 0.0, 0.0]
            init_ori: [0.0, 0.0, 90.0]

    obstacles:
        - bookcase:
            name: "Bookcase 1"
            init_pos: [1.0, 1.0, 0.1]
            init_ori: [0.0, 0.0, 0.0]
        - table:
            name: "Table 1"
            init_pos: [-3.0, 3.0, 0.1]
            init_ori: [0.0, 0.0, 0.0]
        - chair:
            name: "Chair 1"
            init_pos: [-2.0, 2.5, 0.1]
            init_ori: [0.0, 0.0, 0.0]
        - chair:
            name: "Chair 2"
            init_pos: [-2.0, 3.5, 0.1]
            init_ori: [0.0, 0.0, 0.0]
        - chair:
            name: "Chair 3"
            init_pos: [-4.0, 2.5, 0.1]
            init_ori: [0.0, 0.0, 0.0]
        - chair:
            name: "Chair 4"
            init_pos: [-4.0, 3.5, 0.1]
            init_ori: [0.0, 0.0, 0.0]
        - chair:
            name: "Chair 4"
            init_pos: [-4.0, -3.0, 0.1]
            init_ori: [0.0, 0.0, 0.0]
        - chair:
            name: "Chair 5"
            init_pos: [-3.0, -3.0, 0.1]
            init_ori: [0.0, 0.0, 0.0]
        - chair:
            name: "Chair 6"
            init_pos: [-3.0, -4.0, 0.1]
            init_ori: [0.0, 0.0, 0.0]


    robot:
        init_pos: [-4.0, -4.0, 0.0]
        init_ori: [0.0, 0.0, 0.0]
        init_vel: [0.0, 0.0, 0.0]
