name: "Transit"
description: "Navigation Among Movable Obstacles: Simulated Approach"


environment:
    demarcation:
        - wall:
            name: "f-demarcation-wall"
            size: [6.0, 0.2, 0.5]
            init_pos: [0.0, 3.2, 0.0]
            init_ori: [0.0, 0.0, 0.0]
        - wall:
            name: "b-demarcation-wall"
            size: [6.0, 0.2, 0.5]
            init_pos: [0.0, -3.2, 0.0]
            init_ori: [0.0, 0.0, 0.0]
        - wall:
            name: "l-demarcation-wall"
            size: [6.0, 0.2, 0.5]
            init_pos: [-3.2, 0.0, 0.0]
            init_ori: [0.0, 0.0, 90.0]
        - wall:
            name: "r-demarcation-wall"
            size: [6.0, 0.2, 0.5]
            init_pos: [3.2, 0.0, 0.0]
            init_ori: [0.0, 0.0, 90.0]

    obstacles:
        - chair:
            name: "Chair 1"
            init_pos: [1.0, 0.3, 0.1]
            init_ori: [0.0, 0.0, 0.0]
        - chaise:
            name: "Chaise 1"
            init_pos: [1.0, -0.3, 0.1]
            init_ori: [0.0, 0.0, 0.0]

    robot:
        init_state: [0.0, 0.0, 0.0]
