name: "Transfer"
description: "Navigation Among Movable Obstacles: Simulated Approach"


environment:
    demarcation:
        - wall:
            name: "f-demarcation-wall"
            size: [6.0, 0.2, 0.5]
            init_pos: [0.0, 3.2, 0.0]
            init_ori: [0.0, 0.0, 0.0]
        - wall:
            name: "b-demarcation-wall"
            size: [6.0, 0.2, 0.5]
            init_pos: [0.0, -3.2, 0.0]
            init_ori: [0.0, 0.0, 0.0]
        - wall:
            name: "l-demarcation-wall"
            size: [6.0, 0.2, 0.5]
            init_pos: [-3.2, 0.0, 0.0]
            init_ori: [0.0, 0.0, 90.0]
        - wall:
            name: "r-demarcation-wall"
            size: [6.0, 0.2, 0.5]
            init_pos: [3.2, 0.0, 0.0]
            init_ori: [0.0, 0.0, 90.0]
        - wall:
            name: "dividing-wall 1"
            size: [3.0, 0.2, 0.5]
            init_pos: [0.0, -1.7, 0.0]
            init_ori: [0.0, 0.0, 90.0]

    obstacles:
        - chair:
            name: "Chair 1"
            init_pos: [-0.5, 0.0, 0.1]
            init_ori: [0.0, 0.0, 0.0]
        - chair:
            name: "Chair 2"
            init_pos: [-1.5, 0.0, 0.1]
            init_ori: [0.0, 0.0, 0.0]
        - chair:
            name: "Chair 3"
            init_pos: [-2.5, 0.0, 0.1]
            init_ori: [0.0, 0.0, 0.0]
        - chaise:
            name: "Chaise 1"
            init_pos: [0.0, 0.5, 0.1]
            init_ori: [0.0, 0.0, 0.0]
        - chaise:
            name: "Chaise 2"
            init_pos: [0.0, 1.5, 0.1]
            init_ori: [0.0, 0.0, 0.0]
        - chaise:
            name: "Chaise 3"
            init_pos: [0.0, 2.5, 0.1]
            init_ori: [0.0, 0.0, 0.0]


    robot:
        init_state: [-2.5, -2.5, 0.0]
