name: "Vicon"
description: "Navigation Among Movable Obstacles: Simulated Approach"

range_x: [-4.0, 4.0]
range_y: [-4.0, 4.0]

goal: [0., 0.]

camera:
    pos: [-6., 0., 5.]
    tar: [0., 0., 0.]

environment:
    robot:
        init_state: [-2.97, 1.51, 0.]